apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-aws-securitygroup
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-aws-securitygroup
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      This configuration provides a foundation to build and operate AWS SecurityGroup.
    meta.crossplane.io/readme: |
     This configuration is used for deploying and managing AWS SecurityGroup using Crossplane. This setup provides the necessary infrastructure to deploy AWS SecurityGroup with SecurityGroupRules This approach ensures a flexible, streamlined deployment workflow.

     For more details and customization options, you can explore [the GitHub repository](https://github.com/upbound/configuration-aws-securitygroup).
spec:
  crossplane:
    version: ">=v1.14.1-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-aws-network
      # renovate: datasource=github-releases depName=upbound/configuration-aws-network
      version: "v0.14.0"
    - function: xpkg.upbound.io/crossplane-contrib/function-auto-ready
      # renovate: datasource=github-releases depName=crossplane-contrib/function-auto-ready
      version: "v0.2.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-go-templating
      # renovate: datasource=github-releases depName=crossplane-contrib/function-go-templating
      version: "v0.4.1"
