apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xsecuritygroups.aws.platform.upbound.io
spec:
  compositeTypeRef:
    apiVersion: aws.platform.upbound.io/v1alpha1
    kind: XSecurityGroup
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-configuration-aws-securitygroupxsecuritygroups
    step: xsecuritygroups
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
